<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ChatGroup;
use App\Models\Agent;
use App\Services\InternalChatService;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;


class InternalPrivateChatSeeder extends Seeder
{
    function __construct(InternalChatService $internal_chat_service)
    {
        $this->internal_chat_service = $internal_chat_service;
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $all_agents = Agent::get();

        $company = Agent::where('email', 'gina@qwords.co.id')->get(); // specific company
        // $company = Agent::where('id_roles', 2)->get();

        foreach ($company as $key => $value) {
            $current_user = $value;
            $current_user_roles = $value ? $value['id_roles'] : null;
            $agentsInCompany = Agent::where('id_company', $current_user['id'])->get();
            if($agentsInCompany->isNotEmpty()) {
                foreach ($agentsInCompany as $keyAgent => $valAgent) {
                    if( $current_user['id'] && $current_user['uuid'] ) {
                        $room = $this->internal_chat_service->storeFirstChat([
                            'company_id' => $current_user['id'],
                            'uuid' => $current_user['uuid'],
                            'current_user_id' => $current_user['id'],

                            'receiver' => $valAgent['id'],
                        ], 'private');

                        if($room['data'] != null) {
                            $reply_chat = $this->internal_chat_service->replyChat([
                                'company_id' => $current_user['id'],
                                'uuid' => $current_user['uuid'],
                                'current_user_id' => $current_user['id'],

                                'chat_id' => $room['data']['chat_id'],
                                'receiver' => $valAgent['id'],
                                'message' => 'Example test message (generated by system)'
                            ]);
                        }
                    }
                }
            }

        }

    }

}
